package datos;
// Generated 16-oct-2017 23:50:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private int anuncioid;
     private Contacto contacto;
     private Desaparecido desaparecido;
     private Imagen imagen;
     private Usuario usuario;
     private String estado;
     private Date fechacre;
     private Date fechamod;
     private String observacion;
     private Set comentarios = new HashSet(0);

    public Anuncio() {
    }

	
    public Anuncio(int anuncioid, Usuario usuario, String estado) {
        this.anuncioid = anuncioid;
        this.usuario = usuario;
        this.estado = estado;
    }
    public Anuncio(int anuncioid, Contacto contacto, Desaparecido desaparecido, Imagen imagen, Usuario usuario, String estado, Date fechacre, Date fechamod, String observacion, Set comentarios) {
       this.anuncioid = anuncioid;
       this.contacto = contacto;
       this.desaparecido = desaparecido;
       this.imagen = imagen;
       this.usuario = usuario;
       this.estado = estado;
       this.fechacre = fechacre;
       this.fechamod = fechamod;
       this.observacion = observacion;
       this.comentarios = comentarios;
    }
   
    public int getAnuncioid() {
        return this.anuncioid;
    }
    
    public void setAnuncioid(int anuncioid) {
        this.anuncioid = anuncioid;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Desaparecido getDesaparecido() {
        return this.desaparecido;
    }
    
    public void setDesaparecido(Desaparecido desaparecido) {
        this.desaparecido = desaparecido;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechacre() {
        return this.fechacre;
    }
    
    public void setFechacre(Date fechacre) {
        this.fechacre = fechacre;
    }
    public Date getFechamod() {
        return this.fechamod;
    }
    
    public void setFechamod(Date fechamod) {
        this.fechamod = fechamod;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


