package datos;
// Generated 16-oct-2017 23:50:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int contactoid;
     private String nombre;
     private String apellido;
     private String sexo;
     private String parentesco;
     private Integer telefono;
     private String email;
     private Date fechacre;
     private Date fechamod;
     private Set anuncios = new HashSet(0);

    public Contacto() {
    }

	
    public Contacto(int contactoid, String nombre, String apellido) {
        this.contactoid = contactoid;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Contacto(int contactoid, String nombre, String apellido, String sexo, String parentesco, Integer telefono, String email, Date fechacre, Date fechamod, Set anuncios) {
       this.contactoid = contactoid;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sexo = sexo;
       this.parentesco = parentesco;
       this.telefono = telefono;
       this.email = email;
       this.fechacre = fechacre;
       this.fechamod = fechamod;
       this.anuncios = anuncios;
    }
   
    public int getContactoid() {
        return this.contactoid;
    }
    
    public void setContactoid(int contactoid) {
        this.contactoid = contactoid;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechacre() {
        return this.fechacre;
    }
    
    public void setFechacre(Date fechacre) {
        this.fechacre = fechacre;
    }
    public Date getFechamod() {
        return this.fechamod;
    }
    
    public void setFechamod(Date fechamod) {
        this.fechamod = fechamod;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


