package datos;
// Generated 17-oct-2017 1:11:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Desaparecido generated by hbm2java
 */
public class Desaparecido  implements java.io.Serializable {


     private int desaparecidoid;
     private String nombre;
     private String apellido;
     private int edad;
     private String sexo;
     private Integer estatura;
     private String colorpelo;
     private String colorpiel;
     private String vestimenta;
     private String constitucion;
     private String otros;
     private Date fechacre;
     private Date fechamod;
     private Set anuncios = new HashSet(0);

    public Desaparecido() {
    }

	
    public Desaparecido(int desaparecidoid, String nombre, String apellido, int edad, String sexo) {
        this.desaparecidoid = desaparecidoid;
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.sexo = sexo;
    }
    public Desaparecido(int desaparecidoid, String nombre, String apellido, int edad, String sexo, Integer estatura, String colorpelo, String colorpiel, String vestimenta, String constitucion, String otros, Date fechacre, Date fechamod, Set anuncios) {
       this.desaparecidoid = desaparecidoid;
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.sexo = sexo;
       this.estatura = estatura;
       this.colorpelo = colorpelo;
       this.colorpiel = colorpiel;
       this.vestimenta = vestimenta;
       this.constitucion = constitucion;
       this.otros = otros;
       this.fechacre = fechacre;
       this.fechamod = fechamod;
       this.anuncios = anuncios;
    }
   
    public int getDesaparecidoid() {
        return this.desaparecidoid;
    }
    
    public void setDesaparecidoid(int desaparecidoid) {
        this.desaparecidoid = desaparecidoid;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }
    public String getColorpelo() {
        return this.colorpelo;
    }
    
    public void setColorpelo(String colorpelo) {
        this.colorpelo = colorpelo;
    }
    public String getColorpiel() {
        return this.colorpiel;
    }
    
    public void setColorpiel(String colorpiel) {
        this.colorpiel = colorpiel;
    }
    public String getVestimenta() {
        return this.vestimenta;
    }
    
    public void setVestimenta(String vestimenta) {
        this.vestimenta = vestimenta;
    }
    public String getConstitucion() {
        return this.constitucion;
    }
    
    public void setConstitucion(String constitucion) {
        this.constitucion = constitucion;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public Date getFechacre() {
        return this.fechacre;
    }
    
    public void setFechacre(Date fechacre) {
        this.fechacre = fechacre;
    }
    public Date getFechamod() {
        return this.fechamod;
    }
    
    public void setFechamod(Date fechamod) {
        this.fechamod = fechamod;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


